### ISSUE TITLE
Controls for Hang

### ISSUE THREAD

**Issue by billknopfjr** [Team2338/PracticeBot2020#5]
Aux should control so driver can still move bot if necessary.

Hit a button (or buttons) which will engage the hang motor to a set point which allows for the hook to spring out. We do this programmatically so the hook does not hook itself to the bot if the user were to go to fast.
Once the above is complete, use joystick to manually control the hang motor to go up and down
-- this joystick control should not function until the first button has been pressed.

See 2019 code for ComboButtons if we decide to go with multiple buttons:
https://github.com/Team2338/FRC2019/blob/master/src/main/java/team/gif/lib/oi/ComboButton.java

Should also use SmartElevatorPosition
https://github.com/Team2338/FRC2019/blob/master/src/main/java/team/gif/robot/commands/elevator/SmartElevatorPosition.java

**Comment by Jvader314** [comment]
Jittering fixed. Manual Control done.
